# Generated by Django 2.0.2 on 2019-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, upload_to='student_pic/'),
        ),
    ]
