# Generated by Django 2.0.2 on 2019-11-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191023_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, upload_to='student_pic/'),
        ),
    ]
